appname = crm
brand_name = XXCRM
workspace_name = 销售工作台
httpport = 9080
runmode = dev
copyrequestbody = true
EnableGzip = true

#mysql模式
#db_driver = mysql
#db_user = mycrm-test
#db_password =  
#db_host =  
#db_name = mycrm-test

# SQLite3 模式示例：
db_driver = sqlite3
db_path = crm.db

login_user = admin
login_password = admin

uploads=uploads
